# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6ea7129bb03a241f812a0e81e4f0d9864ee2ca6f5fb1f9fbf78169432eba8e078eedfa45c783f0b27ac8758da689fbaacbc6a792220d6d99fb05b7bf8acc7c87

test:
  secret_key_base: e54247ade136d29a5b97ab83f5f4d40bcf7720199416f354393f53f3d383fe61a07359ecb5c0143afc0ce66bbaa92c64bc0fc684da4e270ba6707b43e8ff6366

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
